// src/vue/components/item.vue
<template>
    <div class="item-wrapper card">
        <div class="bg-img-wrapper">
            <img class="bg-img" :src="item.image" alt="" />
        </div>
        <div class="content">
            <div class="item-title">{{ item.title }}</div>
            <div class="item-content">{{ item.content }}</div>
            <br>
            <div>{{ item.owner.name }}</div>
            <div>{{ item.owner.email }}</div>
        </div>
    </div>
</template>

<script>
export default {
    props: ['item']
}
</script>

<style scoped>

</style>

// src/angular/components/item/item.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'Item',
    templateUrl: './item.component.html'
})
export class ItemComponent {
    @Input() item: any;
}
<div class="item-wrapper card">
    <div class="bg-img-wrapper">
        <img class="bg-img" [src]="item.image" alt="" />
    </div>
    <div class="content">
        <div class="item-title">{{ item.title }}</div>
        <div class="item-content">{{ item.content }}</div>
        <br>
        <div>{{ item.owner.name }}</div>
        <div>{{ item.owner.email }}</div>
    </div>
</div>
