// src/vue/components/item.vue
<template>
    <div class="item-wrapper card">
        <div class="bg-img-wrapper">
            <img class="bg-img" :src="item.image" alt="" />
        </div>
        <div class="content">
            <div class="item-title">{{ item.title }}</div>
            <div class="item-content">{{ item.content }}</div>
            <br>
            <div>{{ item.owner.name }}</div>
            <div>{{ item.owner.email }}</div>
        </div>
    </div>
</template>

<script>
export default {
    props: ['item']
}
</script>

<style scoped>

</style>

// src/react/components/item.jsx
import React, { Component } from 'react';

class Item extends Component {

    constructor(prop) {
        super(prop);
    }

    render() {
        return (
            <div class="item-wrapper card">
                <div class="bg-img-wrapper">
                    <img class="bg-img" src={ this.props.item.image } alt="" />
                </div>
                <div class="content">
                    <div class="item-title">{ this.props.item.title }</div>
                    <div class="item-content">{ this.props.item.content }</div>
                    <br/>
                    <div>{ this.props.item.owner.name }</div>
                    <div>{ this.props.item.owner.email }</div>
                </div>
            </div>
        )
    }
}

export default Item;
