// src/vue/App.vue
<template>
    <div class="wrapper">
        <h1>Vue</h1>
        <Item v-for="(item, index) of items" :item="item" v-bind:key="index" />
    </div>
</template>

<script>
import axios from 'axios';
import Item from './components/item.vue';

export default {
    components: {
        Item
    },
    data() {
        return {
            items: []
        }
    },
    created() {
        axios.get('/static/posts.json').then((res) => {
            this.$data.items = res.data;
        }).catch((err) => {

        });
    }
}
</script>

<style>

</style>

// src/react/App.jsx
import React, { Component } from 'react';
import axios from 'axios';
import Item from './components/item.jsx';

class App extends Component {

    constructor(prop) {
        super(prop);
        this.state = {
            items: []
        }
    }

    componentWillMount() {
        axios.get('/static/posts.json').then((res) => {
            this.setState({ items: res.data });
        }).catch((err) => {

        });
    }

    render() {
        return (
            <div class="wrapper">
                <h1>React</h1>
                { this.state.items.map((item, index) => {
                    return ( <Item item={item} /> )
                }) }
            </div>
        );
    }
}

export default App;
