// src/react/App.jsx
import React, { Component } from 'react';
import axios from 'axios';
import Item from './components/item.jsx';

class App extends Component {

    constructor(prop) {
        super(prop);
        this.state = {
            items: []
        }
    }

    componentWillMount() {
        axios.get('/static/posts.json').then((res) => {
            this.setState({ items: res.data });
        }).catch((err) => {

        });
    }

    render() {
        return (
            <div class="wrapper">
                <h1>React</h1>
                { this.state.items.map((item, index) => {
                    return ( <Item item={item} /> )
                }) }
            </div>
        );
    }
}

export default App;

// src/angular/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';
import { map } from 'rxjs/operators';

@Component({
    selector: 'angular-root',
    templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {

    public items: any[] = [];

    constructor(
        private http: Http
    ) {
    }

    ngOnInit() {
        this.http.get('/static/posts.json')
            .pipe(map(res => res.json()))
            .subscribe((res) => {
                this.items = res;
            });
    }
}
<div class="wrapper">
    <h1>Angular</h1>
    <Item *ngFor="let item of items; let i = index" [item]="item"></Item>
</div>
